### ISSUE TITLE
Improve `event.optional` and `event.opional_unique` API

### ISSUE THREAD

**Issue by da-h** [da-h/miniflask#14]
The API regarding `event.optional`, especially `event.optional_unique` seems a bit flawed.

The point of these two differences lies in the fact, that events themselfs can be optional and/or unique.
In that case the event-caller has to decide how the general api of the call looks, i.e.
- in case of optional events: multiple events can be called, thus, multiple results are returned in a list
- in case of optional and unique events: the input is transformed, thus, `optional_unique` returns the input to the calee

Is there maybe a way to improve the api to a more concise user experiance?

**Comment by da-h** [comment]
Idea:
Remove `event.optional_unique` and replace that syntax with:
`event.optional(..., altfn=lambda x: x)`

**Comment by da-h** [comment]
First approach implemented in 9b68d0a.

Although the second approach seems neat, i think it is more important that **optional events are more clearly visually differentiated**.

**Comment by sbrodehl** [comment]
Yes, that is a good approach.
IMHO it is more important that the differences are clearly reflected in the API.

**Comment by da-h** [comment]
Do you feel more can be done in this direction?
If you have any ideas, feel free to contribute. ;)

**Comment by sbrodehl** [comment]
Sure, one can do a lot ;-) but for now this seems like a good solution!
