### ISSUE TITLE
Give default module `miniflask.events` more control

### ISSUE THREAD

**Issue by da-h** [da-h/miniflask#16]
After defining too many modules with many events, the events-module becomes useless.

**Suggestion for Improvement**:
Add 
- [x] a event matching and
- [x] a module matching
query option to this module.

**Comment by sbrodehl** [comment]
Can you please give an example where the events-module becomes useless?

**Comment by da-h** [comment]
It is just an usability issue.
In a different project I use miniflask for, there are around 40 distinct events across all modules.

The module `events` lists all event-names and their corresponding modules they are defined in.
Recently, this list did't help me too much finding the events that I was looking for.

**Comment by sbrodehl** [comment]
Ah right, now I get it.

Query options would indeed be a great improvement here!
Maybe one can create a module which output can be piped through other CLI tools (e.g. grep) so that matching/filtering can be done in the CLI?

**Comment by da-h** [comment]
Done e038a46.
