### ISSUE TITLE
rename set_scope and redefine_scope

### ISSUE THREAD

**Issue by da-h** [da-h/miniflask#23]
Both commands sound very similar, however their used cases are pretty different.
What this actually does should be more visible in the method name.

---

Also, add unit-tests for both functions:
- [ ] `set_scope`
- [x] `register_as`

**Comment by da-h** [comment]
Ideas for replacement names for `set_scope`:
- `use_state(module_id)`
- `share_state(module_id)`
- `use_state_from(module_id)`

Ideas for replacement names for `redefine_scope`:
- `rename_module(module_id)`
- `rename(module_id)`
- `register_module_as(module_id)`

Any thoughts @sbrodehl ?

**Comment by sbrodehl** [comment]
I like `use_state(module_id)` for `set_scope` but with the addition, that a error/warning is thrown, when `module_id` does not exist.
As a replacement for `redefine_scope` I prefer `register_as(module_id)` (or `redefine_as`).

Anyway, their use cases should be added in the docs.

**Comment by da-h** [comment]
If we rename `set_scope` we should also rename the positional argument `scope=...` inside `register_defaults`.

Any ideas for a consistent naming scheme?

Scope is maybe misleading? Maybe we should rename it to namespace?

**Comment by sbrodehl** [comment]
`namespace` sounds about right.
Maybe rename `set_scope` to `use_namespace` as well?

**Comment by da-h** [comment]
After looking more into this, I tend to maintain `set_scope` function unchained.
`redefine_scope`, however has been changed in #57.
