### ISSUE TITLE
List / graph of executed events

### ISSUE THREAD

**Issue by sbrodehl** [da-h/miniflask#24]
The thing I want to see is a list of events (and thus, their order) before their execution - before any execution at all to be precise.

Citing @da-h ideas:
> * One possibility would require a bit of work and a introspection/inspection module in miniflask that analyses all calls to the `event`-object without calling the functions on its own. The downside is, that this will not work in all cases.
> * Another solution would load/call the events normally, but also log the callstack (maybe as a file).

**Comment by da-h** [comment]
At least a starting point is done as of 717e621.
Try to call `./do.py module,events`

**Comment by sbrodehl** [comment]
Thank you!
