### ISSUE TITLE
Feature Request: with statechange

### ISSUE THREAD

**Issue by da-h** [da-h/miniflask#26]
I suggest a with-statement, that changes variables in state only temporarily:

```
with state.temporary({
   "variable1": 42
}):
   # ... do something with the state, e.g.:
   event.call_something_that_uses_states()
```

**Comment by sbrodehl** [comment]
This looks useful, and I think it should be easy to implement.
What is your take on this?

**Comment by da-h** [comment]
Yes. I think so, too.
Feature should be ready tomorrow. ;)

**Comment by sbrodehl** [comment]
Very nice!

**Comment by da-h** [comment]
Done (see commit 1a476c6). :)
