### ISSUE TITLE
Enums as default values

### ISSUE THREAD

**Issue by sbrodehl** [da-h/miniflask#28]
Hi all,

I just run across the _issue_ of using an enum as default value, which is currently not supported.

Here is a small example of what I would like to do:
```python
from enum import Enum
class Color(Enum):
    RED = 1
    GREEN = 2
    BLUE = 3

# ...
# and later use this enum as default value
mf.register_defaults({
    "color": Color.RED
})
```

This fails with the following error:
```python
ValueError: Type '<enum 'Color'>' not supported.
```

Instead, what can be used is the `value` of the enum, like so:
```python
# ...
mf.register_defaults({
    "color": Color.RED.value  # equals 1
})
```

However, using the `value` of the enum has no advantage, since I need to use the integer representation if I want to overwrite it (e.g. `--color 2`).

But if we can use the enum itself, the CLI call to override the value would be something like `--color Color.GREEN`, which IMHO is preferable and very clear.
(Note: I have no idea how the string can be converted to the enum. maybe [this](https://stackoverflow.com/a/55500795)?)

What do you think? Is this a desired feature?

**Comment by da-h** [comment]
Great idea!

I think I have an idea how to tackle this feature. :)

**Comment by da-h** [comment]
Done. (See 200a60d)

Example use:
```python
from enum import Enum

class SIZE(Enum):
    # The integer values define their order in a tensor
    SMALL = 0
    MEDIUM = 1
    LARGE = 2


def main(state, event):
    print("size :", state["size"].name)
    print("sizerequired:", state["sizerequired"].name)
    print("sizelist:", str(" ".join(s.name for s in state["sizelist"])))

def register(mf):
    mf.register_defaults({
        "sizerequired": SIZE,
        "size": SIZE.SMALL,
        "sizelist": [SIZE],
    })
    mf.register_event('main', main)
```

**Comment by sbrodehl** [comment]
Thank you!

**Comment by sbrodehl** [comment]
Hi there,

I have a minor addition to make regarding the use of Enums as default values.
Comparing enum members (e.g. in events) results in unexpected issues, where the comparison fails, even if the members seem identical. I think the underlying issue is a difference in class objects, where multiple instances of the same Enum don't share the same base class object.

This can be circumvented by creating a new Enum member with a given member value, e.g.
```python
if state["size"] is SIZE.SMALL:
    # fails

if SIZE(state["size"].value) is SIZE.SMALL:
    # true
```

**Comment by da-h** [comment]
Thanks for the note, @sbrodehl!

I opened a new issue to that. Possibly, there is a cleaner solution that requires some work in the miniflask core.
