### ISSUE TITLE
Pylint errors and warnings

### ISSUE THREAD

**Issue by sbrodehl** [da-h/miniflask#36]
Here are the (remaining) errors and warnings, which need to be solved the pass the CI.
Since they require a broader knowledge of the code, IMHO it would be best if you could look into it @da-h.

---

### Module `miniflask.event`
- [x] `src/miniflask/event.py`:4:0: **R0903**: Too few public methods (0/2) (too-few-public-methods)
- [x] `src/miniflask/event.py`:8:0: **R0903**: Too few public methods (0/2) (too-few-public-methods)
- [x] `src/miniflask/event.py`:21:4: **W0231**: `__init__` method from base class dict' is not called (super-init-not-called)
- [x] `src/miniflask/event.py`:63:41: **W0621**: Redefining name 'event' from outer scope (line 20) (redefined-outer-name)

### Module `miniflask.state`
- [x] `src/miniflask/state.py`:11:23: **W0621**: Redefining name 'state' from outer scope (line 37) (redefined-outer-name)
- [x] `src/miniflask/state.py`:11:4: **W0231**: `__init__` method from base class 'dict' is not called (super-init-not-called)
- [x] `src/miniflask/state.py`:26:23: **W0622**: Redefining built-in 'type' (redefined-builtin)
- [x] `src/miniflask/state.py`:38:36: **W0621**: Redefining name 'state' from outer scope (line 37) (redefined-outer-name)
- [x] `src/miniflask/state.py`:38:4: **W0231**: `__init__` method from base class 'dict' is not called (super-init-not-called)
- [x] `src/miniflask/state.py`:194:4: **W0235**: Useless super delegation in method '`__getattribute__`' (useless-super-delegation)
- [x] `src/miniflask/state.py`:220:23: **W0621**: Redefining name 'state' from outer scope (line 37) (redefined-outer-name)
- [x] `src/miniflask/state.py`:225:12: **W0621**: Redefining name 'attr' from outer scope (line 4) (redefined-outer-name)

### Module `miniflask.miniflask`
- [x] `src/miniflask/miniflask.py`:440:13: **W0143**: Comparing against a callable, did you omit the parenthesis? (comparison-with-callable)
- [x] `src/miniflask/miniflask.py`:452:11: **W0143**: Comparing against a callable, did you omit the parenthesis? (comparison-with-callable)
- [x] `src/miniflask/miniflask.py`:503:87: **W0640**: Cell variable evt defined in loop (cell-var-from-loop)
- [x] `src/miniflask/miniflask.py`:519:87: **W0640**: Cell variable glob defined in loop (cell-var-from-loop)
- [x] `src/miniflask/miniflask.py`:594:8: **C0200**: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
- [x] `src/miniflask/miniflask.py`:717:15: **W0703**: Catching too general exception Exception (broad-except)
- [x] `src/miniflask/miniflask.py`:735:4: **W0231**: `__init__` method from base class 'miniflask' is not called (super-init-not-called)
- [x] `src/miniflask/miniflask.py`:758:26: **W0621**: Redefining name 'attr' from outer scope (line 11) (redefined-outer-name)

### Module `miniflask.modules.events`
- [x] `src/miniflask/modules/events/__init__.py`:57:0: **R1721**: Unnecessary use of a comprehension (unnecessary-comprehension)

**Comment by da-h** [comment]
Thanks. I will probably check it tomorrow morning.

**Comment by da-h** [comment]
Some Notes:
- `event.py:4` could be replaced by a single-value enum (the class is only used as a dummy-object)
- `event.py:8` the class is basically a struct, so this one is valid. Do you know of some better way to specify this?

**Comment by sbrodehl** [comment]
`event_obj` can use a [namedtuple](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

**Comment by sbrodehl** [comment]
Added the last changes in #39, it would be nice if you can review and test the changes. Thanks!
