### ISSUE TITLE
Replace changes to sys.path

### ISSUE THREAD

**Issue by da-h** [da-h/miniflask#45]
Pytest calls all scripts in one go.

Changing `sys.path` can have unwanted side-effects when defining separate module repositories.

**Comment by sbrodehl** [comment]
In #43 the `sys.path` calls in all tests are replaced by prepending the `module_dirs` with the absolute path to the modules.
This works fine for discovering modules.

Are there any `sys.path` calls in the project itself?

**Comment by da-h** [comment]
Yes, Previously, miniflask based on modifying `sys.path` to import filesystem-wide module repositories.

This has been changed with e974d45.
