### ISSUE TITLE
Don't pollute objects with properties / attributes.

### ISSUE THREAD

**Issue by sbrodehl** [da-h/miniflask#52]
I suggest not to pollute objects with various different properties and attributes related to miniflask, such as `fns`, `fns_args`, `mf_modules` and `subevents`, but use one private (!) variable for this, e.g. `_miniflask`.

**Comment by da-h** [comment]
Good one!

Will include that for the rewrite of `v2`.

**Comment by da-h** [comment]
Changed to v2.1 as this will become more important when implementing child-modules completely.
