### ISSUE TITLE
Thoughts on argument parsing

### ISSUE THREAD

**Issue by sbrodehl** [da-h/miniflask#53]
When registering default values using the `register_defaults` method, I often find myself somewhat limited, especially when
- setting 'empty' values, but requiring a different type (e.g. string value, but `None` as default)
- using uncommon, but standard types (e.g. tuples)
- using custom types (e.g. classes)
- some types change their type (e.g. setting a default value as `[(1, 3)]` will turn into `(1, 3)` - but this is not what is intented?!)
- adding help messages
- providing a list of choices

Currently, to be able to support these usecases these things must be introduced by miniflask, and thus consequently need maintenance, and some may not even be realizable at all.
But so far, every (or at least almost every) issue I faced regarding argument parsing was somewhat _solved_ by the python argparse package.
Therefore I would suggest to rely more on the capabilites of the argparse package by providing a more direct API.

This could look similar to the following (just an idea), where a dict of argparse parameters is passed instead of the actual value:
```python
mf.add_cli_arguments({
    "integers": {metavar='N', type=int, nargs='+', help='an integer for the accumulator'}
    "--sum": {dest='accumulate', action='store_const', const=sum, default=max, help='sum the integers (default: find the max)'}
})
```

Of course, miniflask provides a few additional functionalities, but I think these can be provided by a custom argument parser and action classes.
This way, there would be no need to _reinvent the wheel_ with argument parsing by miniflask.

IMHO it would be an improvement to the current state (code and usability wise) by pushing a few responsibilities to the user and relying more on the argparse package.

What do you think? Is this worth looking into?

**Comment by da-h** [comment]
Could you please give some more details, maybe an example of what you would like to accomplish?

**Comment by da-h** [comment]
By the way, what do you mean by „reinventing the wheel“ ?
Do you have some ideas for a better/clearer api?

I see `miniflask` as a framework that hides the complexity that `argparse` indeed can have, if used extensively.
For instance, regarding the internal method `mf._settings_parser_add`, I do not think, that these kind of calls are great to write instead the much more simpler `register_default` calls that do all of this internally.

**Note**:  
Also, `miniflask` modules can overwrite each others variables, overwriting the variables, that the user can change again over the cli. The cli-output shows then only the changes made by the user. This is so easy to implement, becaus miniflask nows all of its inputs. It could be hard to implement these kind of modules using a more plain argument parsing api.

**Comment by sbrodehl** [comment]
Sorry for the lack of details and the kind of unfriendly tone (I left the issue for a reminder of myself, not as an in-depth discussion).
I updated the issue accordingly, let me know what you think!

**Comment by da-h** [comment]
I think this is a really good idea worth considering for a future release, maybe even replacing the current `register_default` behaviour in the long run!

Until then, I think the best is to merge those two apis:
```
mf.register_defaults({
    "variable": {... argparse arguments ...}
})
```
This way one could fine tune these module parsers, but also just use the api as it is now.

However, positional arguments will probably never make it into miniflask. I mean the cli argument `integers` in your example;
The problem lies in that the module order may be changed by the user, thus positional arguments could result in unintuitive behaviour.
For instance, `python do.py module1,module2` would require `integers` to follow immediately, while `python do.py module2,module1` would result in `integers` to be specified in the end of the call.

Although I like this idea very much, the implementation in the current framework can be a bit tricky. I currently set the priority for this feature to the next milestone (v2.1), however, I will check in the next week wether a first draft of a implementation can be done easily.

**Comment by sbrodehl** [comment]
I don't think merging both is a good idea, because you will run into problems, where both expressions look the same, eventually.
The only viable way to merge these would be (IMHO):
```python
mf.register_defaults({
    "variable": {... argparse arguments ...}
}, argparse=True)
```
to signal miniflask that argparse arguments are to be expected.
Otherwise, a "legacy" dict variable may not be recogniced as such.

Regarding positional arguments: argument parser can be used for this.
There is no need to set modules in the current way `module1,module2,module3`, but could be something like (e.g.) `--module1 --module2 --module3`.
When modules are set as sub-commands and thus as sub-parsers, variable assignments and scopes can be optimized (not saying this is the way to go).

**Comment by da-h** [comment]
At the Moment, there is no way to use dicts for public changeable variables. Even though, `{ ... }` is currently not used by `register_default`, however, it is possible to define a dict as a helper variable (`register_helper`), I tend to admit that these two should not be merged.

Regarding positional arguments:
Would this mean to let modules and variables share the same namespace? What would be your proposed way of specifying also variables in one call?

**Comment by sbrodehl** [comment]
> Regarding positional arguments:
> Would this mean to let modules and variables share the same namespace? What would be your proposed way of specifying also variables in one call?

I have no idea if I understand your question here correctly. What do you mean by namespace? 
but the idea would be to use (nested) argument parsers, something like [this](https://gitlab.com/-/snippets/1752875) or [that](https://gist.github.com/lusis/624782#file-python-argparse-subcommand-subparsers-py).

**Comment by da-h** [comment]
Could you give a more specific example in our case?

I do not see a straight forward way how modules can be expressed using subparsers.
Of course, we could do something like that:
`.do.py module1 --varofmod1 module2 --varofmod2`
For just a few modules, I think this is indeed a feasable way, but the modules that are allowed by miniflask currently can also load other modules automaticall. How would the call look like in that case?

**Comment by da-h** [comment]
I have thought recently about this thread.
**Is this the use of `argparse` still a required feature?**

*My thoughts on how to make this work*:
With the current implementation, it would be possible to include an option to define a custom `argparse`-instance for any variable. This would allow to define new types of variables, actions and filters to be included into the argument parsing.
*However*, I am unsure if and how overwriting these argparse-instances would be possible from another module.
Say, you define a new kind of variable with a specific argument-parsing procedure in one module, and allow another module to adapt that variable. Easiest would be to just let the other module redefine the whole instance again, but tbh. this might become very clumsy very fast.

**What do you think**, @sbrodehl?

**Comment by sbrodehl** [comment]
I don't think it ever was a _required_ feature, more of a way to improve things.
Currently, I think there is no good reason to change the CLI, therefore, I will close this issue.
