### ISSUE TITLE
Outervar not working as intended

### ISSUE THREAD

**Issue by blackliquid** [da-h/miniflask#61]
Miniflask cannot find/use outervar variables in an event _event_0_ if a _before_event_0_ hook is used.

**Comment by da-h** [comment]
Could you please give a complete example and the version you were using?

**Comment by blackliquid** [comment]
Miniflask version 1.3.3

suppose there is a main

def main():
      x = 15
      _event.veryimportantevent()_

and two hooks to that event

mf.register_event('veryimportantevenet, func1)
mf.register_event('before_veryimportantevent', func2) (after also gets the error)

where func2 uses outevar eg.

def func2(*args, x=outervar, **kwargs):
     return args, kwargs

then an exception occurs:

https://pastebin.com/Y38jYmpC

**Comment by da-h** [comment]
Thank you for your description.

I have tested your code against the soon-to-be-published miniflask [v2](https://github.com/da-h/miniflask/tree/v2-dev).
In that version some of these features have received an overhaul.

As far as I can tell, this function does work on the newer branch.

To ensure this functionality in the future, I have also added this test into our test suite. (16ea15c4)

Best,
*da-h*

**Comment by blackliquid** [comment]
Thank you :)
