### ISSUE TITLE
Unknown Variable in 'like' statement

### ISSUE THREAD

**Issue by sbrodehl** [da-h/miniflask#70]
Hi there,

using an unknown variable in a like statement hangs (indefinitely?!)

Here is a short example:
```python
mf.register_defaults({"foobar": like("foobar", 0)})
```
where `foobar` was previously not set.

**Comment by da-h** [comment]
Fixed in commit 4532c24, added also a unit test in 1b7e341 to prevent this kind of bug in the future.
