### ISSUE TITLE
Transform events (before/after event call) not working on `main` event

### ISSUE THREAD

**Issue by sbrodehl** [da-h/miniflask#72]
Here is a _not_ working example (v1.35.2):
```python

def setup():
    print("Not called")


def dummy_main():
    print("Called")


def register(mf):
    mf.register_event("main", dummy_main)
    mf.register_event("before_main", setup)
```

I guess the docs are not clear on the minimum requirements needed to use there transform events.

**Comment by da-h** [comment]
Closing, as this issue is not present anymore in the current `v2-dev`-branch.

More details:
I have added the exact same unit case in commit a3ab4485.
The adaption for this to work has been made in 5afeb05d.
