### ISSUE TITLE
"set-scope()"  behavior modified

### ISSUE THREAD

**Issue by c-ali** [da-h/miniflask#79]
Hi, I dont know if this is intentional, but the "mf.set_scope" function behavior was modified substantially. I previously used it to replace parts (submodules) of a module by different code (eg. a block of a resnet) in a separate module.

Example case: I want to replace grp.model.resnet.blocks.basicblock_pre by a different submodule. Before I could just use 

>     mf.set_scope("grp.model.resnet")

in the replacement module in order to write state-variables in the same scope as the original submodule. Now, even when using the set_scope function, I cannot get rid of the scope of the new module (lola_arch here):

> The following argument is required: --lola_arch.grp.model.resnet.first_conv_kernel_size

Is this intentional? How should I work with these situations?

**Comment by da-h** [comment]
Hi @c-ali,

I am not sure I can follow this issue completely.  

**For next time, please give a self-contained example of your issue**.  
Best is to provide a minimal example of the desired behavior.

**Coming back to your issue**:  
As far as I can tell your description relates to the behavior that `set_scope` is not able to define a global id anymore.
I agree that this is counter intuitive and I have changed this behavior in #87, in queue for the upcoming Release of `Miniflask v2.3`.

**In case this did not solve your issue**, feel free to re-open this thread and specifying the problem in more detail.

Best
*da-h*
